graph TD
    A(["FASE 1 Marktanalyse | A.T.M. N.V.T."]) -->
	B{Aantal kramen > de maximale vraag?}
    B --YES--> strat_1[Indelingsstrategie 1<br>Er volgen in principe geen afwijzingen en er kan worden uitgebreid.]
    B --NO--> C
	C{Aantal kramen > de minimale vraag?}
    C --YES--> strat_2[Indelingsstrategie 2<br>Er volgen in principe geen afwijzingen en er kan beperkt worden uitgebreid.]
    C --NO--> D
	D{Aantal kramen < de minimale vraag?}
    D --YES--> strat_3[Indelingsstrategie 3<br>Er is niet genoeg plaats op de markt, er moeten ondernemers worden afgewezen.]
