graph TD
    A0(["FASE 8 Tijdelijke vasteplaatshouders <b><i>TVPLZ</i></b>"]) --> D
    A1(["FASE 10 Experimentele plaatshouders zonder kramen <b><i>EXP, EXPF</i></b>"]) --> D
    A2(["FASE 11 Sollicitanten <b><i>A-lijst</i></b> met veplichte <b><i>BRANCHE</i></b>"]) --> D
    A3(["FASE 12 Sollicitanten <b><i>A-lijst</i></b> met <b><i>BAK</i></b>"]) --> D
    A4(["FASE 13 Sollicitanten <b><i>A-lijst</i></b> met <b><i>EVI</i></b>"]) --> D
    A5(["FASE 14 Sollicitanten <b><i>A-lijst</i></b> , <b><i>Overige</i></b>"]) --> D
    
    D[Deel de ondernemers in op de plaatsen van hun voorkeur indien mogelijk<br>Zie diagram: 'vinden kramen'] -->
    E{"Strategie? (Nog nvt)"}
    E --"Strategie 1 of 2 (ruimte op de markt)"--> E2(["Deel de sollicitanten in voor 1 kraam en verplaats<br> voor de extra kramen de ondernemer naar de uitbreidings wachtrij."])
    E --"Strategie 3 (te weinig ruimte)"--> E3(["Sorteer op sollicitatienummer en begin bij het laagste nummer,<br> de overgebleven ondernemers krijgen een afwijzing."])