graph TD
    A2(["FASE 23 uitbreidingsfase (b-lijst)"]) -->
    C2("Selecteer de ondernemers uit de uitbreidingswachtrij met<br> een <b><i>BRANCHE</i></b> en op de <b><i>B-lijst</i></b>") --> D
    
    A3(["FASE 24 uitbreidingsfase (b-lijst)"]) -->
    C3("Selecteer de ondernemers uit de uitbreidingswachtrij met<br> een <b><i>BAK</i></b> en op de <b><i>B-lijst</i></b>") --> D
    
    A4(["FASE 25 uitbreidingsfase (b-lijst)"]) -->
    C4("Selecteer de ondernemers uit de uitbreidingswachtrij met<br> een <b><i>EVI</i></b> en op de <b><i>B-lijst</i></b>") --> D
    
    A5(["FASE 26 uitbreidingsfase (b-lijst)"]) -->
    C5("Selecteer de <b><i>overige</i></b> ondernemers uit de uitbreidingswachtrij op de <b><i>B-lijst</i></b>") --> D

    D[Haal de reeds toegewezen plaatsen op<br> voor deze ondernemer] -->
    F{Is er een plek die aansluit en<br> toegewezen kan worden? <b><br><br>BRANCHE<br>BAK<br>EVI</b>}
    F --JA plek gevonden--> F1(["Toewijzing uitbreiding,<br> (zie diagram 'vinden uitbreiding')"])
    F --NEE geen plek gevonden--> F2([Uitbreiden niet mogelijk])
    
