graph TD
    A([FASE 3-b toestaan verplaatsing]) --> 
    B(Probeer de voorkeursplaatsen van de ondernemers) -->
    B1{Is de plaats vrij of kan vrij<br> komen door ruil/doorschuiven?}
    B1 --NEE--> C
    B1 --JA--> D
    C(Zet de ondenemers die niet kunnen verplaatsen op de vaste plaatsen)
    D(Kijk of er ondernemers zijn die van plaatsen willen ruilen) -->
    E(Deel de ondenemers in op de ruilplekken) -->
    F(Probeer de overige ondernemers in te delen op de voorkeursplaatsen) -->
    G{"Is er een conflict bij de verplaatsing?<br> (zelfde voorkeuren)"}
    G --JA--> VP(Deel in op vasteplaatsen)
    G --NEE--> VKP(Deel in op voorkeursplaatsen)
    G --"Niet zeker (er zijn nog opties)"--> while
    while{Zijn er nog verplaatsers over?}
    while --JA--> F
    while --NEE--> 
    done([Alle verplaatsers zijn ingedeeld op<br> de nieuwe plaats of vasteplaats])
