graph TD
    A([FASE 3 VPL + TVPL verplaatsing]) -->
    B[Selecteer alle VPL en TVPL<br> die willen verplaatsen en deel ze<br> in op de voorkeursplaatsen indien beschikbaar] -->
    C{Verplaatsing toegestaan?}
    C --YES--> D(["Deel in op voorkeursplaats(en) de-queue ondernemer en kraam"])
    C --NO--> E(["Deel in op vasteplaats(en) de-queue ondernemer en kraam"])

