graph TD
    A(["FASE 10-a uitbreidingsfase)"]) -->
    C(Selecteer de ondernemers uit de uitbreidingsstack met<br> een verplichte branche en op de A-lijst) -->
    D[Haal de reeds toegewezen plaatsen op<br> voor deze ondernemer] -->
    F{Is er een plek die aansluit en<br> toegewezen kan worden?}
    F --JA plek gevonden--> F1(["Toewijzing uitbreiding,<br> (zie diagram 'vinden uitbreiding')"])
    F --NEE geen plek gevonden--> F2([Uitbreiden niet mogelijk])
    
    Ab(["FASE 10-b uitbreidingsfase)"]) -->
    Cb(Selecteer de ondernemers uit de uitbreidingsstack met<br> een verplichte branche en op de B-lijst) -->
    Db[Haal de reeds toegewezen plaatsen op<br> voor deze ondernemer] -->
    Fb{Is er een plek die aansluit en<br> toegewezen kan worden?}
    Fb --JA plek gevonden--> F1b(["Toewijzing uitbreiding,<br> (zie diagram 'vinden uitbreiding')"])
    Fb --NEE geen plek gevonden--> F2b([Uitbreiden niet mogelijk])
    
    Ac(["FASE 10-c uitbreidingsfase)"]) -->
    Cc(Selecteer de ondernemers uit de uitbreidingsstack met<br> een EVI en op de A-lijst) -->
    Dc[Haal de reeds toegewezen plaatsen op<br> voor deze ondernemer] -->
    Fc{Is er een plek die aansluit en<br> toegewezen kan worden?}
    Fc --JA plek gevonden--> F1c(["Toewijzing uitbreiding,<br> (zie diagram 'vinden uitbreiding')"])
    Fc --NEE geen plek gevonden--> F2c([Uitbreiden niet mogelijk])
    
    Ad(["FASE 10-d uitbreidingsfase)"]) -->
    Cd(Selecteer de ondernemers uit de uitbreidingsstack met<br> een EVI en op de B-lijst) -->
    Dd[Haal de reeds toegewezen plaatsen op<br> voor deze ondernemer] -->
    Fd{Is er een plek die aansluit en<br> toegewezen kan worden?}
    Fd --JA plek gevonden--> F1d(["Toewijzing uitbreiding,<br> (zie diagram 'vinden uitbreiding')"])
    Fd --NEE geen plek gevonden--> F2d([Uitbreiden niet mogelijk])
