graph TD
    A([FASE 2 VPL]) -->
	B{Selecteer de vasteplaatshouders<br> die niet willen verplaatsen<br> en deel ze in op de vast plaatsen.}
    B --plaats beschikbaar--> C([Dequeue ondernemer, dequeue marktplaats])
    B --plaats niet beschikbaar--> D([Vaste plaatsen dienen beschikbaar te zijn,<br> rapporteer fout aan marktbureau.])
    
    A2([FASE 2-b TVPL]) -->
	B2{Selecteer de tijdelijke vasteplaatshouders<br> die niet willen verplaatsen<br> en deel ze in op de vast plaatsen.}
    B2 --plaats beschikbaar--> C2([Dequeue ondernemer, dequeue marktplaats])
    B2 --plaats niet beschikbaar--> D2([Vaste plaatsen dienen beschikbaar te zijn,<br> rapporteer fout aan marktbureau.])
