graph TD
    A(["FASE 12-a uitbreidingsfase)"]) -->
    C("Selecteer de ondernemers (geen  EVI geen verplichte branche)<br> uit de uitbreidingsstack op de A-lijst") -->
    D[Haal de reeds toegewezen plaatsen op<br> voor deze ondernemer] -->
    F{Is er een plek die aansluit en<br> toegewezen kan worden?}
    F --JA plek gevonden--> F1(["Toewijzing uitbreiding,<br> (zie diagram 'vinden uitbreiding')"])
    F --NEE geen plek gevonden--> F2([Uitbreiden niet mogelijk])
    
    Ab(["FASE 12-b uitbreidingsfase)"]) -->
    Cb("Selecteer de ondernemers (geen EVI geen verplichte branche)<br> uit de uitbreidingsstack op de B-lijst") -->
    Db[Haal de reeds toegewezen plaatsen op<br> voor deze ondernemer] -->
    Fb{Is er een plek die aansluit en<br> toegewezen kan worden?}
    Fb --JA plek gevonden--> F1b(["Toewijzing uitbreiding,<br> (zie diagram 'vinden uitbreiding')"])
    Fb --NEE geen plek gevonden--> F2b([Uitbreiden niet mogelijk])
