graph TD
    A([FASE 5 SOLL A-lijst met EVI]) -->
    C[Selecteer de ondernemers uit de gesorteerde lijst met een EVI en A-lijst] -->
    D[Deel de ondernemers in op de plaatsen van hun voorkeur indien mogelijk<br>Zie diagram: 'vinden kramen'] -->
    E{Strategie?}              
    E --"Strategie 1 (genoeg ruimte)"--> E1(["Deel de sollicitanten in voor MIN kramen en verplaats<br> voor de extra kramen de ondernemer naar de uitbreidings stack."])
    E --"Strategie 2 (beperkt ruimte)"--> E2(["Deel de sollicitanten in voor 1 kraam en verplaats<br> voor de extra kramen de ondernemer naar de uitbreidings stack."])
    E --"Strategie 3 (te weinig ruimte)"--> E3(["Sorteer op sollicitatienummer en begin bij het laagste nummer,<br> de overgebleven ondernemers krijgen een afwijzing."])
