graph TD
    A([FASE 14 Sollicitanten <b><i>B-lijst</i></b> met veplichte <b><i>BRANCHE</i></b>]) -->
    D[Deel de ondernemers in op de plaatsen van hun voorkeur indien mogelijk<br>Zie diagram: 'vinden kramen'] -->
    E{Strategie?}              
    E --"Strategie 1 of 2 (ruimte op de markt)"--> E2(["Deel de sollicitanten in voor 1 kraam en verplaats<br> voor de extra kramen de ondernemer naar de uitbreidings wachtrij."])
    E --"Strategie 3 (te weinig ruimte)"--> E3(["Sorteer op sollicitatienummer en begin bij het laagste nummer,<br> de overgebleven ondernemers krijgen een afwijzing."])

    A2([FASE 15 Sollicitanten <b><i>B-lijst</i></b> met <b><i>BAK</i></b>]) --> D
    A3([FASE 16 Sollicitanten <b><i>B-lijst</i></b> met <b><i>EVI</i></b>]) --> D
    A4([FASE 17 Sollicitanten <b><i>B-lijst</i></b> , <b><i>Overige</i></b>]) --> D
