graph TD
    D[Haal de reeds toegewezen plaatsen op<br> voor deze ondernemer] -->
    F{Is er een plek die aansluit en<br> toegewezen kan worden? <b><br><br>BRANCHE<br>BAK<br>EVI</b>}
    F --JA plek gevonden--> F1(["Toewijzing uitbreiding,<br> (zie diagram 'vinden uitbreiding')"])
    F --NEE geen plek gevonden--> F2([Uitbreiden niet mogelijk])
    
    A(["FASE 12 uitbreidingsfase"]) -->
    C("Selecteer de <b><i>vasteplaatshouders</i></b> (vpl, tvpl en tvplz) uit de uitbreidingswachtrij") --> D
    A2(["FASE 13 uitbreidingsfase"]) -->
    C2("Selecteer de ondernemers uit de uitbreidingswachtrij met<br> een <b><i>BRANCHE</i></b> en op de <b><i>A-lijst</i></b>") --> D
    A3(["FASE 14 uitbreidingsfase"]) -->
    C3(Selecteer de ondernemers uit de uitbreidingswachtrij met<br> een <b><i>BAK</i></b> en op de <b><i>A-lijst</i></b>) --> D
    A4(["FASE 15 uitbreidingsfase"]) -->
    C4(Selecteer de ondernemers uit de uitbreidingswachtrij met<br> een <b><i>EVI</i></b> en op de <b><i>A-lijst</i></b>) --> D
    A5(["FASE 16 uitbreidingsfase"]) -->
    C5(Selecteer de <b><i>overige</i></b>ondernemers uit de uitbreidingswachtrij op de <b><i>A-lijst</i></b>) --> D
