graph TD
    A([Vinden van geschikte uitbreiding voor een al ingedeelde ondernemer.]) -->
    B("Zoek een 'n' aantal aaneengesloten kramen. (een optie)") -->
    C{Vallen de al toegewezen kramen binnen<br> het cluster van deze optie?}
    C --JA--> C1(Selecteer deze optie) --> D
    C --NEE--> C2(Selecteer deze optie nu niet,<br> eventueel later als voorkeuren niet beschikbaar zijn.)
    D{Is deze optie valide m.b.t branche?}
    D --JA--> E
    D --NEE--> D2([Optie niet geldig])
    E{Is deze optie valide m.b.t EVI?}
    E --JA--> F
    E --NEE--> E2([Optie niet geldig])
    F{Is deze optie nog beschikbaar?}
    F --JA--> OK(Voeg toe aan beschikbare opties) --> DONE
    F --NEE--> F2([Optie niet geldig])
    DONE([Beschikbare opties])
